version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Wissem123!
      MYSQL_DATABASE: employee_management_system
    ports:
      - "3306:3306"
    networks:
      - employee-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Monte le script d'initialisation

  springboot-backend:
    container_name: springboot-backend-container
    build: 
      context: springboot-backend/
    image: springboot-backend-image  
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_management_system?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Wissem123!
    depends_on:
      - mysql
    networks:
      - employee-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: Wissem123!
    ports:
      - "8081:80"
    networks:
      - employee-network
    depends_on:
      - mysql


  angular-frontend:
    container_name: angular-frontend-container
    build:
      context: angular-frontend/
    image: angular-frontend-image
    ports:
      - "4200:80" # Mapping du port HTTP (Nginx ou Angular)
    networks:
      - employee-network
    depends_on:
      - springboot-backend



networks:
  employee-network:
    driver: bridge

volumes:
  mysql-data:

